FROM python:3.11-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    dnsutils \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY otel_watcher_test.py /app/

CMD ["python3", "/app/otel_watcher_test.py"]
